services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: src/serving_layer
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: mydb
      DB_PORT: 5432
      DATABASE_URL: postgres://admin:admin@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  streamlit_app:
    build: streamlit_app
    environment:
      SERVING_LAYER_ADDRESS: http://api:8000
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: mydb
      DB_PORT: 5432
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app

  computation-layer:
    build:
      context: ./src/computation_layer
      dockerfile: Dockerfile
    container_name: computation-layer
    environment:
      DB_DSN: postgresql://admin:admin@postgres:5432/mydb
    depends_on:
      - postgres
    restart: unless-stopped

volumes: {}
